server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Service 1: Weather
    # Replaces /api/weather with /api/v1
    location /api/weather/ {
        proxy_pass https://weather-aggregator-aggregator-service-app:9000/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		proxy_ssl_trusted_certificate /etc/nginx/certs/weather-aggregator-ca.crt;
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 2;
		
    }

    # Service 2: Auth
    # Replaces /api/auth with /api/v1/auth
    location /api/auth/ {
        proxy_pass https://weather-aggregator-user-identity-service-app:9010/api/v1/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Required for cookies/sessions
        proxy_pass_header Set-Cookie;
        proxy_set_header Cookie $http_cookie;
		
		proxy_ssl_trusted_certificate /etc/nginx/certs/weather-aggregator-ca.crt;
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 2;
    }

    # Service 3: User Preferences
    # Replaces /api/user with /api/v1/user
    location /api/user/ {
        proxy_pass https://weather-aggregator-user-preferences-service-app:9011/api/v1/user/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	
		proxy_ssl_trusted_certificate /etc/nginx/certs/weather-aggregator-ca.crt;
		proxy_ssl_verify on;
		proxy_ssl_verify_depth 2;
    }
}