FROM rust:1.92.0-slim

RUN apt-get update && apt-get install -y \
    lld clang pkg-config libssl-dev
  
WORKDIR /app

# Copy manifest and resolve dependencies early (Docker cache)
COPY Cargo.toml Cargo.lock ./

RUN mkdir -p src/org/unibl/etf \
 && echo "// fake lib" > src/lib.rs \
 && echo "fn main() {}" > src/org/unibl/etf/main.rs \
 && cargo build --release \
 && rm -rf src


EXPOSE 9003

